# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('user_name', models.CharField(default=b'\xe5\x8c\xbf\xe5\x90\x8d', max_length=20)),
                ('kind', models.CharField(choices=[(b'Python\xe6\x8a\x80\xe6\x9c\xaf', b'Python\xe6\x8a\x80\xe6\x9c\xaf'), (b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe6\x8a\x80\xe6\x9c\xaf', b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe6\x8a\x80\xe6\x9c\xaf'), (b'\xe7\xbb\x8f\xe6\xb5\x8e\xe5\xad\xa6', b'\xe7\xbb\x8f\xe6\xb5\x8e\xe5\xad\xa6'), (b'\xe5\x85\xb6\xe4\xbb\x96', b'\xe5\x85\xb6\xe4\xbb\x96')], default=(b'Python\xe6\x8a\x80\xe6\x9c\xaf', b'Python\xe6\x8a\x80\xe6\x9c\xaf'), max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': '\u535a\u5ba2', 'verbose_name_plural': '\u535a\u5ba2'},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98'),
        ),
    ]
